### PR TITLE
Add TeamID to VehicleDestroy and Death event models

### PR DESCRIPTION
**Pull request by nlioc4**
Very short PR as I realized this feature hadn't been added yet.
I know it's not very profesional, so feel free to reject if you'd rather do it better yourself!

### CODE REVIEW

**Comment by leonhard-s** [comment]
Thanks for the PR - it looks like some tests are failing due to validation errors.

I dont think those use any static test data, so Ill have a look to see if I can fix/add some tests to cover this.

**Comment by leonhard-s** [comment]
Finally had time to give this a proper look - the tests were failing because the `team_id` of the victim is still missing for both `Death` and `VehicleDestroy`.

The unused `vehicle_id` field also appears to have been removed from the `Death` event payload. I'm fixing this on upstream right now.

**Comment by nlioc4** [comment]
In hindsight, this PR would likely have been better posed as an Issue instead

**Comment by leonhard-s** [comment]
I would have amended this PR but multi-line or -file suggestions are sadly not supported very well.

Your change has been cherry-picked and tests fixed, thank you for the contribution!

**Pull request closed without merging**
