### PR TITLE
Draft of rewriting event models

### PR DESCRIPTION
**Pull request by LordFlashmeow**
I went all-out on implementing pydantic models for the websocket responses. I thought it was a cool idea to let pydantic parse the messages, starting with the raw payload text all the way to the models.

Let me know your thoughts and if there's anything you'd like to keep.

### CODE REVIEW

**Review by leonhard-s — COMMENTED** [review]
Finally got around to looking at this in detail. Here are some thoughts, in no particular order:

* I don't think having the full pydantic model vs. implementation duality for event payloads is worth it; these events cannot be interacted with in the same way the regular ps2 object model can. Whatever getters or utility we do want to include should be possible in the pydantic models, too.

* Likewise, I don't see a reason to wrap the other WebSocket payloads in pydantic models since they are only used internally to manage the trigger/listener system.

* I quite like the separation into character vs. world events. This could be used to provide better errors if the user decides to subscript to continent lock events while specifying specific character IDs, for example.

The last point does make me question the current trigger system again. It currently still relies on the user knowing how events work, without any errors or other indications that some subscriptions are bogus.

**Comment by LordFlashmeow** [comment]
Maybe we can hold the users' hand a little and give them warnings by making the Event models subclasses of WorldEvent and CharacterEvent, and then a function to verify the subscription before sending it.

**Comment by leonhard-s** [comment]
Something like that, yeah - I've started a draft of merging our two implementations locally, but I got a bit side-tracked trying to resolve all the partially-imported-modules needing to talk to each other (models require bases, bases require models to validate triggers, triggers now take these models as arguments...).

Not too happy with my work-in-progress, but I'll make a PR tomorrow once I found a solution for the import shenanigans.

**Comment by LordFlashmeow** [comment]
I chose to make a util file that didn't import from anything and move what I could into there. After that I ended up consolidating a bunch of files to cut down on imports. Definitely headache-inducing!

**Comment by leonhard-s** [comment]
Closing this PR as it has been integrated into the larger #43 refactor.

Thank you again for this request; the commits got buried a bit behind an larger restructuring, but the event portion of that draft is now very similar to your original work here.

**Pull request closed without merging**
